name: flake8

on:
  [ push, pull_request ]
  
permissions:
  contents: read
  checks: write

jobs:
  flake8_py3:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        name: setup Python
        with:
          python-version: '3.12'
      - name: Checkout pygeoapi
        uses: actions/checkout@master
      - name: Install flake8
        run: pip3 install flake8
      - name: Run flake8
        run: >
          flake8
          pygeoapi/api/movingfeatures.py
          pygeoapi/api/collection.py
          pygeoapi/flask_app.py
          pygeoapi/openapi.py
          pygeoapi/provider/postgresql_mobilitydb.py
          --extend-ignore=E501
